// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#include "lvgl_ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(lv_obj_t *parent);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

