// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui_Screen1.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Checkbox1 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_TextArea5 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(lv_obj_t *parent)
{
    ui_Screen1 = lv_obj_create(parent);
    lv_obj_set_size(ui_Screen1, lv_pct(100), lv_pct(100));
    lv_obj_align(ui_Screen1, LV_ALIGN_CENTER, 0, 0);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Checkbox1 = lv_checkbox_create(ui_Screen1);
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1, -23);
    lv_obj_set_y(ui_Checkbox1, 31);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 33);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 122);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Click ME!");
    lv_label_set_recolor(ui_Label2, "true");

    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 53);
    lv_obj_set_height(ui_Spinner1, 51);
    lv_obj_set_x(ui_Spinner1, 3);
    lv_obj_set_y(ui_Spinner1, -59);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x00C275), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 20, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 150);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, -6);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Dropdown2 = lv_dropdown_create(ui_Screen1);
    lv_obj_set_width(ui_Dropdown2, 150);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 0);
    lv_obj_set_y(ui_Dropdown2, 75);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_TextArea5 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea5, 156);
    lv_obj_set_height(ui_TextArea5, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_TextArea5, 0);
    lv_obj_set_y(ui_TextArea5, -120);
    lv_obj_set_align(ui_TextArea5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea5, "g");

    lv_obj_set_style_text_color(ui_TextArea5, lv_color_hex(0x171717), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea5, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Checkbox1 = NULL;
    ui_Button1 = NULL;
    ui_Label2 = NULL;
    ui_Spinner1 = NULL;
    ui_Bar1 = NULL;
    ui_Dropdown2 = NULL;
    ui_TextArea5 = NULL;

}
