// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui_Screen3.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(lv_obj_t *parent)
{
    ui_Screen3 = lv_obj_create(parent);
    lv_obj_set_size(ui_Screen3, lv_pct(100), lv_pct(100));
    lv_obj_align(ui_Screen3, LV_ALIGN_CENTER, 0, 0);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Screen3);
    lv_obj_set_width(ui_TextArea1, 150);
    lv_obj_set_height(ui_TextArea1, 70);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Label4 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -52);
    lv_obj_set_y(ui_Label4, -48);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Chat:");

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, 165);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, -1);
    lv_obj_set_y(ui_Panel2, -109);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch3 = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_Switch3, 50);
    lv_obj_set_height(ui_Switch3, 25);
    lv_obj_set_x(ui_Switch3, 43);
    lv_obj_set_y(ui_Switch3, -1);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Switch3, LV_STATE_CHECKED);       /// States

    ui_Label6 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -43);
    lv_obj_set_y(ui_Label6, 1);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Location");

    ui_Button2 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 37);
    lv_obj_set_x(ui_Button2, 0);
    lv_obj_set_y(ui_Button2, 71);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Send");

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_TextArea1 = NULL;
    ui_Label4 = NULL;
    ui_Panel2 = NULL;
    ui_Switch3 = NULL;
    ui_Label6 = NULL;
    ui_Button2 = NULL;
    ui_Label7 = NULL;

}
