// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui_Screen2.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Calendar1 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(lv_obj_t *parent)
{
    ui_Screen2 = lv_obj_create(parent);
    lv_obj_set_size(ui_Screen2, lv_pct(100), lv_pct(100));
    lv_obj_align(ui_Screen2, LV_ALIGN_CENTER, 0, 0);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_Screen2);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 166);
    lv_obj_set_height(ui_Calendar1, 240);
    lv_obj_set_x(ui_Calendar1, -2);
    lv_obj_set_y(ui_Calendar1, -35);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);

    ui_Button4 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 37);
    lv_obj_set_x(ui_Button4, -4);
    lv_obj_set_y(ui_Button4, 122);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "OK");

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Calendar1 = NULL;
    ui_Button4 = NULL;
    ui_Label8 = NULL;

}
