// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#include "lvgl_ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(lv_obj_t *parent);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Calendar1;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

