// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#include "lvgl_ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(lv_obj_t *parent);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Checkbox1;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_TextArea5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

